### ISSUE TITLE
Can't "List Queries" {Resolved: Global Queries aren't currently supported}

### ISSUE THREAD

**Issue by KyleKing** [tosher/Redlime#10]
Right now, nothing happens when selecting any of `Redlime issue: Create` or `Redlime: List Queries` from the Sublime command palette, but view/editing issues & `Redlime: Project Issues` all work.

Should the custom queries appear when clicking on list queries? Can I enter a subset of custom query IDs?

These are my user settings:

```json
{
    "redmine_url": "http://internal.redmine.com/redmine",
    "api_key": "<removed>",
    "projects_filter": ["project-a", "project-b"],
    "assigned_to_group_id_filter": [],
    "query_page_size": 50,
    "issue_list_columns": [
        { "prop": "id", "colname": "#", "custom": false, "align": "right" },
        { "prop": "project", "colname": "Project", "custom": false},
        { "prop": "priority", "colname": "Prior.", "custom": false},
        { "prop": "status", "colname": "Status", "custom": false},
        { "prop": "author", "colname": "Author", "custom": false},
        { "prop": "assigned_to", "colname": "Assigned", "custom": false},
        { "prop": "subject", "colname": "Subject", "custom": false, "maxlen": 30},
        { "prop": "due_date", "colname": "Due Date", "custom": false, "type": "datetime"},
        { "prop": "done_ratio", "colname": "% Done", "custom": false, "type": "progressbar"}
    ],
    "issue_view_columns": [
        { "prop": "id", "colname": "Issue", "custom": false},
        { "prop": "project", "colname": "Project", "custom": false},
        { "prop": "status", "colname": "Status", "custom": false},
        { "prop": "priority", "colname": "Priority", "custom": false},
        { "prop": "done_ratio", "colname": "Done ratio", "custom": false, "type": "progressbar"},
        { "prop": "author", "colname": "Author", "custom": false},
        { "prop": "assigned_to", "colname": "Assigned to", "custom": false},
        { "prop": "created_on", "colname": "Creation date", "custom": false, "type": "datetime"}
    ]
}
```

**Comment by tosher** [comment]
I'll check queries list - it must work if queries really exists in rm.
But, Issue creation must work.. do you see some errors in ST's console?

**Comment by KyleKing** [comment]
For issue creation, I was able to make progress.

I accidentally had 17 in the `assigned_to_group_id_filter` which reported this error:
```
Traceback (most recent call last):
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\base\rl_issue_create.py", line 42, in on_project_done
    for user in self.redmine.user.filter(group_id=group_id):
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\resultsets.py", line 102, in __iter__
    self._evaluate()
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\resultsets.py", line 81, in _evaluate
    offset=self.manager.params.get('offset', self.offset)
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\managers.py", line 62, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\__init__.py", line 136, in request
    raise ForbiddenError
Redlime.libs.redmine.exceptions.ForbiddenError: Requested resource is forbidden
```

Removing the incorrect 17 got me farther, but after entering the subject, I get the below error that one of our required custom fields is missing:
```
Traceback (most recent call last):
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\base\rl_issue_create.py", line 97, in on_subject_done
    issue.save()
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\base\../libs\redmine\resources.py", line 257, in save
    for item, value in self.manager.create(**self._changes):
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\managers.py", line 191, in create
    response = self.redmine.request('post', url, data=data)
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\libs\redmine\__init__.py", line 147, in request
    raise ValidationError(to_string(', '.join(e if is_string(e) else ': '.join(e) for e in errors)))
Redlime.libs.redmine.exceptions.ValidationError: Desired Completion Date cannot be blank
```
This may not be easily solvable, so and I'm okay with not being able to create tickets. I can create new time entries, which will be way more useful!


I would really like to use the custom queries, so any help solving that would be appreciated. There doesn't appear to be any info printed to the console for this issue

**Comment by KyleKing** [comment]
I tried "list queries" again and was able to get an error message in the console.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 490, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\redlime.py", line 39, in on_activated_async
    cols=cols
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\base\shortcuts_menu.py", line 86, in __init__
    line = self.html_shortcut_tpl % {'keyname': self.show_key(shortcuts[k][0]), 'cmdname': shortcuts[k][1]}
  File "C:\Users\king.kyle\AppData\Roaming\Sublime Text 3\Packages\Redlime\base\shortcuts_menu.py", line 110, in show_key
    keys = keyname.split('+')
AttributeError: 'NoneType' object has no attribute 'split'
```

These are my queries (example .../issues?query_id=34):

![queries_list](https://user-images.githubusercontent.com/3784339/40133411-ad50f610-590d-11e8-9e1c-6976c4d3d738.PNG)

**Comment by tosher** [comment]
Thanks for the info, i'll check it.

**Comment by tosher** [comment]
Please, tell me the version of Redmine. I've checked the issue creation and queries on the latest version and can't to reproduce this errors.

**Comment by KyleKing** [comment]
Hi @tosher, I was out on vacation and just got back. The version is 3.4.4.stable

**Comment by tosher** [comment]
These queries are available inside some project or they are global, by all projects? 

At this moment, only project's queries are supported.

**Comment by KyleKing** [comment]
Oh okay, all of my queries were global. I tried some project-specific queries and they worked

**Comment by KyleKing** [comment]
Are you interested in PRs? I could take a look at adding Global Queries and configuring custom fields for new issue creation

**Comment by tosher** [comment]
You are welcome! :)
