### ISSUE TITLE
Comment on issue view fails in 2 column layout

### ISSUE THREAD

**Issue by softloft38p-michael** [tosher/Redlime#12]
If I am in 2 column layout and try to invoke the comment command from an issue page, it fails:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 490, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/redlime.py", line 39, in on_activated_async
    cols=cols
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/base/shortcuts_menu.py", line 86, in __init__
    line = self.html_shortcut_tpl % {'keyname': self.show_key(shortcuts[k][0]), 'cmdname': shortcuts[k][1]}
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/base/shortcuts_menu.py", line 110, in show_key
    keys = keyname.split('+')
AttributeError: 'NoneType' object has no attribute 'split'
```

Switching back to single view layout allows the comment command to execute.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Redlime/releases/tag/v1.6.2

**Comment by softloft38p-michael** [comment]
Looks like it's working now.
