### ISSUE TITLE
Can't create new issues

### ISSUE THREAD

**Issue by softloft38p-michael** [tosher/Redlime#13]
When trying to create new issues, the following error shows in the console:

```
Redlime.libs.redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist
Traceback (most recent call last):
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/base/rl_issue_create.py", line 46, in on_project_done
    self.users = [self.redmine.user.get(user.user.id) for user in self.redmine.project_membership.filter(project_id=self.issue_data['project_id']) if hasattr(user, 'user')]
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/base/rl_issue_create.py", line 46, in <listcomp>
    self.users = [self.redmine.user.get(user.user.id) for user in self.redmine.project_membership.filter(project_id=self.issue_data['project_id']) if hasattr(user, 'user')]
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/managers/base.py", line 87, in get
    raise e
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/managers/base.py", line 83, in get
    return self.to_resource(self.redmine.engine.request('get', self.url, params=self.params)[self.container])
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/engines/base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/engines/base.py", line 157, in process_response
    raise exceptions.ResourceNotFoundError
Redlime.libs.redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist
```

Every other function of redlime seems to work.

**Comment by tosher** [comment]
* Which version of Redmine are you using? 
* This error shows after selecting redmine project or after user selecting for issue assign? The selected project has members to assign an issue?

**Comment by softloft38p-michael** [comment]
We're using Redmine version 3.3.2. I can usually pull up the projects menu and select a project, but then it does nothing afterward. The project does have members. I can create issues through the site and it works correctly.

Unfortunately, I'm not able to check for error messages in the console after selecting a project because I'm getting this error on load: 

```python
reloading plugin Redlime.redlime
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/redlime.py", line 6, in <module>
    from .base import *  # noqa
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/base/__init__.py", line 4, in <module>
    from .rl_editbox import RedlimeEditboxSaveCommand
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/base/rl_editbox.py", line 7, in <module>
    from . import rl_utils as utils
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/base/rl_utils.py", line 10, in <module>
    from ..libs.redmine import Redmine
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/__init__.py", line 11, in <module>
    from . import managers, exceptions, engines, utilities, resources
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/engines/__init__.py", line 6, in <module>
    from .sync import SyncEngine
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/engines/sync.py", line 6, in <module>
    from ..packages import requests
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/Redlime/libs/redmine/packages/__init__.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'
```

**Comment by tosher** [comment]
Are you using the Package control to install/update the plugin?

**Comment by softloft38p-michael** [comment]
Yes. This is after uninstalling and reinstalling due to these errors.

**Comment by tosher** [comment]
Please, check with new version:
https://github.com/tosher/Redlime/releases/tag/v1.6.3
