### ISSUE TITLE
Certificate verify failed when using a custom ssl cert

### ISSUE THREAD

**Issue by gimco** [tosher/Redlime#5]
If the configured redmine server uses a self-generated https certificate we'll get the next error:

~~~
Traceback (most recent call last):
  File "~/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "~/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "~/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "~/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "~/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "./python3.3/ssl.py", line 246, in wrap_socket
  File "./python3.3/ssl.py", line 350, in __init__
  File "./python3.3/ssl.py", line 346, in __init__
  File "./python3.3/ssl.py", line 553, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
~~~

**Comment by gimco** [comment]
For the record, we can set this settings to disable certificate validation:

~~~
{
    "redmine_url" : "https://internal-server-with-custom-ssl/redmine",
    "connection_options" : {
        "verify": false
    },
~~~

Maybe we can add this tip on the Readme or describe then `connection_options` setting.

* http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
